service: my-first-service
app: my-first-app
org: leebyeongdo

plugins:
  - "@silvermine/serverless-plugin-cloudfront-lambda-edge"

provider:
  name: aws
  runtime: nodejs12.x

resources:
  Resources:
    CloudFrontDistribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Logging:
            Bucket: test-website-bucket-byeongdolee.s3.amazonaws.com
            IncludeCookies: false
            Prefix: sls
          DefaultCacheBehavior:
            AllowedMethods:
              - "GET"
              - "HEAD"
            TargetOriginId: bdbdbdlee-cf-test-origin-id
            ForwardedValues:
              QueryString: false
              Headers:
                - "isEmployee"
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 86400
            ViewerProtocolPolicy: allow-all
          Enabled: true
          IPV6Enabled: true
          PriceClass: "PriceClass_All"
          HttpVersion: "http2"
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          Origins:
            - DomainName: rocky-anchorage-37851.herokuapp.com
              CustomOriginConfig:
                OriginProtocolPolicy: match-viewer
                OriginSSLProtocols:
                  - "TLSv1"
              Id: bdbdbdlee-cf-test-origin-id
    LambdaAtEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambda-at-edge-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  cfLambda:
    handler: handler.hello
    role: LambdaAtEdgeRole
    memorySize: 128
    timeout: 3
    lambdaAtEdge:
      distribution: "CloudFrontDistribution"
      eventType: "viewer-request"
